import type { BlueprintObject } from '../types/jobsite'; import type { PdfPageGeometry } from './pdfPlanGeometry';
import { READING_PLAN_SHA256 } from './gradingPipeline'; import type { PublishedWaterPackage } from './waterPipeline';
export type DryUtilityCandidate={id:string;kind:'light_bollard';label:string;confidence:'medium';labelPriority:number;planPoint:{x:number;y:number};provenance:{sourceSha256:string;sheet:'Topographic Survey';pdfPage:2;sourceText:string[];sourceItemIndexes:number[];extraction:'manual_vector_review';status:'reference-derived'}};
export type DryUtilityDraft={projectId:'reading-public-library';sheet:'Topographic Survey';pdfPage:2;sourceSha256:string;candidates:DryUtilityCandidate[];pendingEvidence:Array<{source:string;reason:string}>;excludedEvidence:Array<{source:string;reason:string}>;limitations:string[]};
export type DryUtilityReviewDecision={candidateId:string;decision:'approved'|'rejected';reviewer:string};
export type PublishedDryUtilityPackage=Omit<PublishedWaterPackage,'packageVersion'|'contentHash'|'reviews'|'sourceLedger'>&{packageVersion:'reading-public-library-grading-sanitary-storm-water-dry-v5';contentHash:string;reviews:PublishedWaterPackage['reviews']&{dryUtility:{reviewer:string;approvedCandidateIds:string[];rejectedCandidateIds:string[]}};sourceLedger:Array<unknown>};
export function buildReadingDryUtilityDraft(geometry:PdfPageGeometry,sourceSha256:string):DryUtilityDraft{
 if(sourceSha256!==READING_PLAN_SHA256)throw new Error('The source checksum does not match the locked Reading bid set.'); if(geometry.pageNumber!==2)throw new Error('Dry-utility evidence is locked to PDF page 2.');
 const make=(id:string,x:number,y:number,p:number):DryUtilityCandidate=>({id,kind:'light_bollard',label:'Existing LIGHT BOLLARD · west walk',confidence:'medium',labelPriority:p,planPoint:{x,y},provenance:{sourceSha256,sheet:'Topographic Survey',pdfPage:2,sourceText:['LIGHT BOLLARD'],sourceItemIndexes:[],extraction:'manual_vector_review',status:'reference-derived'}});
 return{projectId:'reading-public-library',sheet:'Topographic Survey',pdfPage:2,sourceSha256,candidates:[make('survey-light-bollard-west-north',18,40,320),make('survey-light-bollard-west-south',21,47,310)],pendingEvidence:[{source:'OHW overhead-wire corridor',reason:'The survey shows an overhead-wire corridor, but an exact defensible trace was not established.'},{source:'Utility pole symbols',reason:'No symbol-by-symbol source review established publishable pole assets.'}],excludedEvidence:[{source:'SP1.1 page 3 protect existing light pole',reason:'Corroboration only, not another mapped asset.'},{source:'Legend-only electric, cable, telephone, and gas symbols',reason:'Legend entries are not mapped assets.'},{source:'Generic utility structures and lines',reason:'System identity is not established.'},{source:'Water, storm, and sanitary assets',reason:'Outside the dry-utility layer.'}],limitations:['OHW geometry and utility poles remain pending; no voltage, ownership, connectivity, underground linework, or system attributes are published.','Survey utility locations are approximate surface evidence from manual vector review.','This layer is not for construction staking; verify utility records, field locates, and survey control.']};
}
const toObject=(c:DryUtilityCandidate):BlueprintObject=>({id:c.id,type:'light_pole',layerId:'dry-utility',x:c.planPoint.x,y:c.planPoint.y,label:c.label,workerLabel:'LIGHT BOLLARD',symbol:'dry-light-bollard',labelPriority:c.labelPriority,confidence:c.confidence,blueprintSheet:'Topographic Survey',provenance:c.provenance,notes:'OHW geometry is unavailable. Survey utility location is approximate surface evidence. Not for construction staking.'});
function hashText(v:string){let h=0x811c9dc5;for(let i=0;i<v.length;i+=1){h^=v.charCodeAt(i);h=Math.imul(h,0x01000193);}return(h>>>0).toString(16).padStart(8,'0');} function deepFreeze<T>(v:T):T{if(v&&typeof v==='object'&&!Object.isFrozen(v)){Object.freeze(v);for(const c of Object.values(v as Record<string,unknown>))deepFreeze(c);}return v;}
export function publishApprovedDryUtilityPackage(base:PublishedWaterPackage,draft:DryUtilityDraft,decisions:DryUtilityReviewDecision[],publishedAt:string):PublishedDryUtilityPackage{const byId=new Map(decisions.map(d=>[d.candidateId,d]));if(byId.size!==draft.candidates.length||draft.candidates.some(c=>!byId.has(c.id)))throw new Error('Publishing requires an explicit review decision for every dry-utility candidate.');if(decisions.some(d=>!d.reviewer.trim()))throw new Error('Every dry-utility decision must identify the reviewer.');const approved=draft.candidates.filter(c=>byId.get(c.id)?.decision==='approved'),rejected=draft.candidates.filter(c=>byId.get(c.id)?.decision==='rejected');const{packageVersion:_v,contentHash:_h,reviews,...rest}=base;void _v;void _h;const core={...rest,publishedAt,packageVersion:'reading-public-library-grading-sanitary-storm-water-dry-v5' as const,layers:[...base.layers,{id:'dry-utility',name:'Dry Utilities',color:'#a16207',defaultVisible:true}],objects:[...base.objects,...approved.map(toObject)],utilities:[...base.utilities],reviews:{...reviews,dryUtility:{reviewer:decisions[0]?.reviewer??'Unknown reviewer',approvedCandidateIds:approved.map(c=>c.id),rejectedCandidateIds:rejected.map(c=>c.id)}},sourceLedger:[...base.sourceLedger,{fileName:'25020-RPL_Bid_Drawings_2025_07_11.pdf',sha256:draft.sourceSha256,sheet:'Topographic Survey',pdfPage:2,authority:'survey',status:'reference-derived'}],limitations:[...base.limitations,...draft.limitations,...draft.pendingEvidence.map(e=>`${e.source}: ${e.reason}`)]};return deepFreeze({...core,contentHash:hashText(JSON.stringify(core))}) as PublishedDryUtilityPackage;}
