const state={projects:[],active:null,operation:null};
const $=(id)=>document.getElementById(id);
const esc=(value)=>String(value??'').replace(/[&<>"']/g,(char)=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[char]));
async function api(path,options={}){const response=await fetch(path,{headers:{'Content-Type':'application/json'},...options});const body=await response.json();if(!response.ok)throw new Error(body.error||`Request failed (${response.status})`);return body}
function notice(message,error=false){const el=$('notice');el.hidden=!message;el.textContent=message||'';el.className=`notice${error?' error':''}`}
function renderProjects(){const list=$('project-list');if(!state.projects.length){list.innerHTML='<p class="guardrail">No projects yet.</p>';return}list.innerHTML=state.projects.map(project=>`<button class="project-button ${state.active?.slug===project.slug?'active':''}" data-slug="${esc(project.slug)}"><strong><i class="project-status ${project.validation_status==='valid'?'valid':''}"></i>${esc(project.name)}</strong><small>${esc(project.revision)} · ${project.issue_count} gate${project.issue_count===1?'':'s'}</small></button>`).join('');list.querySelectorAll('button').forEach(button=>button.onclick=()=>selectProject(button.dataset.slug))}
function renderProvenance(provenance){const values=Object.values(provenance);const max=Math.max(1,...values);$('provenance').innerHTML=Object.entries(provenance).map(([label,count])=>`<div class="provenance-row"><span>${esc(label.replace('_',' '))}</span><strong>${count}</strong><div class="provenance-track"><i style="width:${count/max*100}%"></i></div></div>`).join('')}
function renderIssues(issues){$('issue-count').textContent=`${issues.length} active`;$('issues').innerHTML=issues.length?issues.map(issue=>`<article class="issue ${issue.review?'reviewed':''}"><i class="issue-marker"></i><div><strong>${esc(issue.code)}</strong><code>${esc(issue.path)}</code><p>${esc(issue.message)}${issue.review?` · Reviewed by ${esc(issue.review.reviewer)}; gate remains active.`:''}</p></div><button data-key="${esc(issue.key)}" data-label="${esc(issue.code)}">${issue.review?'Update note':'Review'}</button></article>`).join(''):'<div class="no-issues">Canonical validation reports no active errors.</div>';$('issues').querySelectorAll('button').forEach(button=>button.onclick=()=>openReview(button.dataset.key,button.dataset.label))}
function duration(seconds){const value=Number(seconds||0);if(value<60)return `${value.toFixed(value<10?1:0)}s`;const minutes=Math.floor(value/60);const remainder=Math.round(value%60);return `${minutes}m ${remainder}s`}
function renderObservation(workflow_observation){const observation=workflow_observation||{};const inputs=observation.inputs||{};const decisions=observation.decisions||{};const outputs=observation.outputs||{};const timing=observation.timing||{};$('observation-stage').textContent=(observation.stage||'intake').replaceAll('_',' ');$('current-action').textContent=observation.current_action||'Lock source evidence and verify job controls.';$('observation-revision').textContent=observation.job_control?.revision||'draft';$('source-lock-count').textContent=`${inputs.locked_source_count||0} / ${inputs.source_count||0}`;$('human-review-count').textContent=decisions.human_review_required||0;$('automated-time').textContent=duration(timing.automated_seconds);$('manual-time').textContent=duration(timing.manual_seconds);$('result-classification').textContent=(observation.result_classification||'not_assessed').replaceAll('_',' ');$('evidence-list').innerHTML=(inputs.evidence||[]).length?(inputs.evidence||[]).map(source=>`<div><strong>${esc(source.title||source.id)}</strong><span>${esc(source.provenance_status)} · ${esc(source.lock_status)}${source.sha256?` · ${esc(source.sha256.slice(0,16))}…`:''}</span></div>`).join(''):'<p>No source evidence is registered.</p>';const artifactRows=(outputs.artifacts||[]).map(name=>`<div><strong>${esc(name)}</strong><span>Canonical run artifact</span></div>`);if(outputs.publication)artifactRows.push(`<div><strong>Immutable Field Map handoff</strong><span>${esc(outputs.publication.import_file)}</span></div>`);$('output-list').innerHTML=artifactRows.length?artifactRows.join(''):'<p>No current run outputs.</p>';$('touch-list').innerHTML=(observation.operator_touches||[]).length?(observation.operator_touches||[]).slice(0,5).map(touch=>`<div><strong>${esc(touch.activity.replaceAll('_',' '))} · ${duration(touch.duration_seconds)}</strong><span>${esc(touch.note)} · ${esc(touch.result_classification.replaceAll('_',' '))}</span></div>`).join(''):'<p>No operator touches recorded.</p>'}
function latestRun(){return state.active?.current_run}
function renderRun(run=latestRun()){const ready=run?.publication_readiness==='ready';$('progress-bar').style.width=run?'100%':'0';$('run-stage').textContent=run?run.stage.replaceAll('_',' '):'Not started';$('run-detail').textContent=run?`${run.status} · ${run.run_id}`:'Validation → artifacts → parity';$('artifact-list').innerHTML=run?Object.keys(run.artifacts||{}).map(name=>`<span class="artifact">${esc(name)}</span>`).join(''):'';$('readiness-badge').textContent=ready?'Ready':'Blocked';$('readiness-badge').className=`chip ${ready?'':'blocked'}`;$('readiness-copy').textContent=ready?'Validation and artifact parity passed. Publish will create an immutable, content-addressed local handoff.':'A passing canonical validation and artifact parity report are required.';$('publish').disabled=!ready;$('publish').dataset.runId=run?.run_id||''}
function renderProject(){const project=state.active;$('empty-state').hidden=!!project;$('workspace').hidden=!project;if(!project)return;$('project-name').textContent=project.name;$('project-meta').textContent=`${project.project_id} · ${project.revision} · ${project.project_file}`;$('input-count').textContent=`${project.input_count} file${project.input_count===1?'':'s'}`;$('validation-chip').textContent=project.validation_status;$('validation-chip').className=`chip ${project.validation_status}`;renderObservation(project.workflow_observation);renderProvenance(project.provenance);const groups=project.readiness_inventory?.groups||{};$('readiness-groups').innerHTML=Object.entries(groups).map(([name,group])=>`<details><summary>${esc(name.replaceAll('_',' '))} · ${group.blocker_count}</summary><p>${esc(group.next_action)}</p></details>`).join('');renderIssues(project.issues);renderRun();renderProjects()}
async function refreshProjects(){state.projects=await api('/api/projects');renderProjects()}
async function selectProject(slug){state.active=await api(`/api/projects/${encodeURIComponent(slug)}`);notice('');$('publication-result').textContent='';renderProject()}
async function createProject(event){event.preventDefault();const submitter=event.submitter;if(submitter?.value==='cancel')return $('project-dialog').close();const data=Object.fromEntries(new FormData(event.currentTarget));try{const project=await api('/api/projects',{method:'POST',body:JSON.stringify(data)});$('project-dialog').close();event.currentTarget.reset();await refreshProjects();await selectProject(project.slug)}catch(error){notice(error.message,true);$('project-dialog').close()}}
function fileBase64(file){return new Promise((resolve,reject)=>{const reader=new FileReader();reader.onload=()=>resolve(String(reader.result).split(',')[1]);reader.onerror=reject;reader.readAsDataURL(file)})}
async function ingest(file){if(!state.active||!file)return;notice(`Locking ${file.name}…`);try{const content_base64=await fileBase64(file);const source=await api(`/api/projects/${state.active.slug}/inputs`,{method:'POST',body:JSON.stringify({filename:file.name,content_base64})});notice(`${source.filename} locked · ${source.sha256.slice(0,16)}… · provenance remains unknown`);await refreshProjects();await selectProject(state.active.slug)}catch(error){notice(error.message,true)}}
async function runPipeline(){if(!state.active)return;$('run-pipeline').disabled=true;$('progress-bar').style.width='8%';$('run-stage').textContent='Queued';$('current-action').textContent='Waiting for the supervised canonical pipeline operation to start.';notice('Canonical pipeline started.');try{const op=await api(`/api/projects/${state.active.slug}/runs`,{method:'POST',body:'{}'});state.operation=op.operation_id;pollOperation()}catch(error){notice(error.message,true);$('run-pipeline').disabled=false}}
async function pollOperation(){try{const op=await api(`/api/operations/${state.operation}`);$('progress-bar').style.width=`${op.progress_percent}%`;$('run-stage').textContent=op.stage.replaceAll('_',' ');$('automated-time').textContent=duration(op.elapsed_seconds);$('current-action').textContent=op.status==='running'?'Canonical validation, artifact build, and parity checks are running.':'Waiting for the canonical operation.';if(op.status==='complete'){notice(op.result.publication_readiness==='ready'?'Run passed every publication gate.':'Run stopped at fail-closed validation.');$('run-pipeline').disabled=false;await refreshProjects();await selectProject(op.project_slug);return}if(op.status==='failed'){throw new Error(op.error)}setTimeout(pollOperation,350)}catch(error){notice(error.message,true);$('run-pipeline').disabled=false}}
function openReview(key,label){const form=$('review-form');form.elements.issue_key.value=key;$('review-issue').textContent=`${label} remains a blocking validator outcome.`;$('review-dialog').showModal()}
async function submitReview(event){event.preventDefault();if(event.submitter?.value==='cancel')return $('review-dialog').close();const payload=Object.fromEntries(new FormData(event.currentTarget));try{await api(`/api/projects/${state.active.slug}/reviews`,{method:'POST',body:JSON.stringify(payload)});$('review-dialog').close();event.currentTarget.reset();notice('Review note recorded. The validation gate remains active until the canonical model passes.');await selectProject(state.active.slug)}catch(error){notice(error.message,true);$('review-dialog').close()}}
async function submitOperatorTouch(event){event.preventDefault();if(!state.active)return;const payload=Object.fromEntries(new FormData(event.currentTarget));payload.minutes=Number(payload.minutes);try{await api(`/api/projects/${state.active.slug}/touches`,{method:'POST',body:JSON.stringify(payload)});event.currentTarget.reset();notice('Operator time and evidence note recorded without changing validation gates.');await selectProject(state.active.slug)}catch(error){notice(error.message,true)}}
async function publish(){const runId=$('publish').dataset.runId;if(!runId)return;try{const publication=await api(`/api/projects/${state.active.slug}/publish`,{method:'POST',body:JSON.stringify({run_id:runId})});$('publication-result').innerHTML=`Import file:<br><strong>${esc(publication.import_file)}</strong>`;notice(`Immutable publication ${publication.publication_id.slice(0,16)}… created.`)}catch(error){notice(error.message,true)}}
$('new-project').onclick=()=>$('project-dialog').showModal();$('project-form').addEventListener('submit',createProject);$('review-form').addEventListener('submit',submitReview);$('operator-touch-form').addEventListener('submit',submitOperatorTouch);$('plan-input').onchange=(event)=>ingest(event.target.files[0]);$('run-pipeline').onclick=runPipeline;$('publish').onclick=publish;const zone=$('dropzone');['dragenter','dragover'].forEach(name=>zone.addEventListener(name,event=>{event.preventDefault();zone.classList.add('dragging')}));['dragleave','drop'].forEach(name=>zone.addEventListener(name,event=>{event.preventDefault();zone.classList.remove('dragging')}));zone.addEventListener('drop',event=>ingest(event.dataTransfer.files[0]));refreshProjects().then(()=>state.projects[0]&&selectProject(state.projects[0].slug)).catch(error=>notice(error.message,true));
